# Use a imagem oficial do PHP com Apache
FROM php:7.4-apache

# Copie os arquivos do projeto para o diretório de trabalho do Apache
COPY busca-site/ /var/www/html/

# Exponha a porta 80 para o Apache
EXPOSE 80
